name:                som
version:             10.1.0
github:              "mhwombat/som"
license:             BSD3
author:              "Amy de Buitléir"
maintainer:          "amy@nualeargais.ie"
copyright:           "2012-2018 Amy de Buitléir"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Self-Organising Maps
category:            Math

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/mhwombat/som#readme>

dependencies:
  - base >= 4.7 && < 5

library:
  source-dirs: src
  ghc-options:
  - -Wall
  dependencies:
    - containers
    - deepseq
    - grid

tests:
  som-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - containers
    - deepseq
    - grid
    - QuickCheck
    - random
    - som
    - test-framework
    - test-framework-quickcheck2
